variable "aws_region" {
  description = "(Optional) This is the AWS region. It must be provided, but it can also be sourced from the AWS_DEFAULT_REGION environment variables, or via a shared credentials file if profile is specified."
  default = "us-east-1"
}

variable "subnet_id" {
  description = "(Required) The ID of the subnet to add the mount target in."
}

variable "lifecycle_policy" {
  description = "(Optional) A file system lifecycle policy object (documented below)."
  default = "AFTER_30_DAYS"
}

variable "creation_token" {
  description = "(Optional) A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. See [Elastic File System] (http://docs.aws.amazon.com/efs/latest/ug/) user guide for more information."
}